// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7DnpiK0xGe_cQMv90hhnu2QnR4U5zpoA',
    appId: '1:149554145339:web:5287a3fd223769005f141e',
    messagingSenderId: '149554145339',
    projectId: 'login-app-1575a',
    authDomain: 'login-app-1575a.firebaseapp.com',
    storageBucket: 'login-app-1575a.firebasestorage.app',
    measurementId: 'G-GGMJ5B8VVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjzVf7d9DWXafbKK643M634R24fi0bjTU',
    appId: '1:149554145339:android:acbb901c939a83ad5f141e',
    messagingSenderId: '149554145339',
    projectId: 'login-app-1575a',
    storageBucket: 'login-app-1575a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIxpUK76FEqRC8gcaBt9VyyvqPDYwJxAM',
    appId: '1:149554145339:ios:eacb7b84b65cefb15f141e',
    messagingSenderId: '149554145339',
    projectId: 'login-app-1575a',
    storageBucket: 'login-app-1575a.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIxpUK76FEqRC8gcaBt9VyyvqPDYwJxAM',
    appId: '1:149554145339:ios:eacb7b84b65cefb15f141e',
    messagingSenderId: '149554145339',
    projectId: 'login-app-1575a',
    storageBucket: 'login-app-1575a.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7DnpiK0xGe_cQMv90hhnu2QnR4U5zpoA',
    appId: '1:149554145339:web:62dcb16ad2880c3e5f141e',
    messagingSenderId: '149554145339',
    projectId: 'login-app-1575a',
    authDomain: 'login-app-1575a.firebaseapp.com',
    storageBucket: 'login-app-1575a.firebasestorage.app',
    measurementId: 'G-H6L7YZRLJC',
  );
}
